name: Mode Examen

on:
  schedule:
    - cron: '15 11 * * *' # Active le mode exam à 10h UTC (ajuste selon ton fuseau horaire)
    - cron: '18 11 * * *' # Désactive le mode exam à 11h UTC

jobs:
  update-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Activer/Désactiver le mode exam
        run: |
          heure=$(date +"%H")
          if [ "$heure" -eq "10" ]; then
            echo "Mode Examen activé" > mode.txt
          else
            echo "Mode Examen désactivé" > mode.txt
          fi

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add mode.txt
          git commit -m "Mise à jour du mode exam"
          git push
